### ISSUE TITLE
support for codeberg and other lesser used platforms

### ISSUE THREAD

**Issue by artix-boi** [Sanix-Darker/zzollo#35]

**Comment by Sanix-Darker** [comment]
If it's possible, can you provide the list you have in mind here ?
Thanks !

**Comment by artix-boi** [comment]
there are many small platforms, codeberg, gitea, idk all. But maybe what can be done is a way for user to add these languages and the search syntax, which then can be sent to us to add in master branch?

**Comment by Sanix-Darker** [comment]
Closing this issue due to none activity since !
Feel free to trigger this feature again when you want !
