### ISSUE TITLE
[Feature] Infinite/All repos toggle 

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Sanix-Darker/zzollo#45]
I like how the pagination looks and works. It's beautiful. But I think it would be sick if you could make a toggle that could switch from pagination to the old layout that showed all the repositories. And make the toggle remember what you set it as. 

For example: 
If the toggle is on, the next time I open the site, it should remember and turn on. 
The old design allowed me to use the ctrl+f, which would help me filter down the repositories further and help me find the repo I wanted. Here it looks cool and cleaner but makes this process a bit more tedious.

**Comment by Sanix-Darker** [comment]
> [Feature] Infinite/All repos toggle  #45
    Open • ChrisFarmer-dev opened about 13 hours ago • 0 comments

      I like how the pagination looks and works. It's beautiful. But I think it
      would be sick if you could make a toggle that could switch from pagination
      to the old layout that showed all the repositories. And make the toggle
      remember what you set it as.

      For example:
      If the toggle is on, the next time I open the site, it should remember and
      turn on.
      The old design allowed me to use the ctrl+f, which would help me filter down
      the repositories further and help me find the repo I wanted. Here it looks
      cool and cleaner but makes this process a bit more tedious.

Your proposition is fair enought to be a new feature in Zzollo but it's a side configuration that is not urgent at the moment, you're free to make a Pull Request about it !
Thanks for this feature contribution !

**Comment by ChrisFarmer-dev** [comment]
@njammy sorry for disturbing youu, could you please try to make this 🙏. I am just learning to code so I cannot figure this out 😭 . If its not possible or you are busy then it's okayy I understand.

Thank you so much 🙏

**Comment by njammy** [comment]
> @njammy sorry for disturbing youu, could you please try to make this 🙏. I am just learning to code so I cannot figure this out 😭 . If its not possible or you are busy then it's okayy I understand.
> 
> Thank you so much 🙏

alrigth i will try to make it 😭😭😭

**Comment by ChrisFarmer-dev** [comment]
Thank you so muchh 🙏 🫂

**Comment by njammy** [comment]
hello @ChrisFarmer-dev  i added the possibility to see all result as in the last version, but not the option to save the state of this, i added too but during testing isn't user friendly for the new user which activate this option and when they come back (all the result will be rendered whithout pagination according to you need) it look like the pagination isn't integrated also, so i just submit the feat mentionned above in the pr

**Comment by ChrisFarmer-dev** [comment]
hii @njammy Ohh okayy. I just saw your PR screenshot it looks so good, Thank you so muchh :pray: 🫂. If it does not save the option it's not a problem since you made it easily accessible. Thank you so muchh 🙏

**Comment by Sanix-Darker** [comment]
I will close this since, it seems to be resolved !
