### ISSUE TITLE
[Feature] Gist search

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Sanix-Darker/zzollo#49]
Add Gist search (in the `From [Github / GitLab / Bitbucket]` dropdown). There are times that I find useful stuff in Gists like snippets and other stuff. It would be really nice if I could just use zzollo and find it. 

Thank you so much 🙏 

![image](https://user-images.githubusercontent.com/71568799/184009240-d6ee3785-f06c-49e2-9b4d-5776324a3f2d.png)

**Comment by Sanix-Darker** [comment]
If am not wrong, gists are not working like that !
From the github API, you need :
1- to be authenticated before performing requests on github gist API
2- to perform your requests, you need to have the author username in advance (https://docs.github.com/en/rest/gists/gists#list-gists-for-a-user)

**Comment by ChrisFarmer-dev** [comment]
> If am not wrong, gists are not working like that ! From the github API, you need : 1- to be authenticated before performing requests on github gist API 2- to perform your requests, you need to have the author username ([docs.github.com/en/rest/gists/gists#list-gists-for-a-user](https://docs.github.com/en/rest/gists/gists#list-gists-for-a-user))

Ohh okk that's a bummer np. Thank you so much 🙏 I will close this issue then.
