### ISSUE TITLE
Remove Scale Up animation on hover

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/zzollo#60]
We should reduce the amount of animation on the projects list rendering !

**Comment by mobo07** [comment]
Hi @Sanix-Darker , I would love to handle this issue if no one has been assigned it yet.

**Comment by Sanix-Darker** [comment]
It's yours !
Thank you !

**Comment by Sanix-Darker** [comment]
Thanks for this Pull Request @mobo07 👍🏾 !
