### ISSUE TITLE
Add a scroll to the top floating button

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/zzollo#68]
In case we scrolled down with pagination deactivated, we could need to get at the top really quickly to access search filters, and this could be done with a floating button !

**Comment by HanslettTheDev** [comment]
let me fork this repo. I can contribute heavily here.

**Comment by Sanix-Darker** [comment]
Thanks @HanslettTheDev , sorry, this issue was closed but : https://github.com/Sanix-Darker/zzollo/pull/77
But feel free to contribute on other issues where you feel comfortable !
