### ISSUE TITLE
Your Cert was hijacked

### ISSUE THREAD

**Issue by skiffkiddie** [Sanix-Darker/zzollo#98]
Please check the zzollo site you host, it seems to be hijacked by hackers ?

>  Firefox does not trust this site because it uses a certificate that is not valid for zzollo.co. The certificate is only valid for the following names: *.apnigiftshop.com, apnigiftshop.com
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
>  
> View Certificate

**Comment by dy05** [comment]
Its seems like the domain name is not more available, i think, he will fix this very soon.

**Comment by Sanix-Darker** [comment]
Thanks for reporting this, the new domain is available here : https://zollo.sanixdk.xyz/ 🙂

**Comment by Sanix-Darker** [comment]
Please reopen this if you still have the same kind of issue.
